import { z } from "zod";

/** Branding is compile-time only; the wire value remains a UUID string. */
export function brandedId<T extends string>(name: T) {
  return z.uuid().describe(name).brand<T>();
}

/** Pass a UUID v7 generated by the host's platform ID service. */
export function createBrandedId<S extends z.ZodType<string>>(schema: S, value: string): z.infer<S> {
  return z.parse(schema, value);
}

export const SecretId = brandedId("SecretId");
export type SecretId = z.infer<typeof SecretId>;

export const IdentityId = brandedId("IdentityId");
export type IdentityId = z.infer<typeof IdentityId>;

export const ProviderId = brandedId("ProviderId");
export type ProviderId = z.infer<typeof ProviderId>;

export const ModelId = brandedId("ModelId");
export type ModelId = z.infer<typeof ModelId>;

export const VectorStoreId = brandedId("VectorStoreId");
export type VectorStoreId = z.infer<typeof VectorStoreId>;

export const DocumentId = brandedId("DocumentId");
export type DocumentId = z.infer<typeof DocumentId>;

export const ConversationId = brandedId("ConversationId");
export type ConversationId = z.infer<typeof ConversationId>;

export const MessageId = brandedId("MessageId");
export type MessageId = z.infer<typeof MessageId>;

export const ScenarioId = brandedId("ScenarioId");
export type ScenarioId = z.infer<typeof ScenarioId>;

export const RunId = brandedId("RunId");
export type RunId = z.infer<typeof RunId>;

export const StepId = brandedId("StepId");
export type StepId = z.infer<typeof StepId>;

export const SkillId = brandedId("SkillId");
export type SkillId = z.infer<typeof SkillId>;

export const McpServerId = brandedId("McpServerId");
export type McpServerId = z.infer<typeof McpServerId>;

export const ToolId = brandedId("ToolId");
export type ToolId = z.infer<typeof ToolId>;

export const IntegrationId = brandedId("IntegrationId");
export type IntegrationId = z.infer<typeof IntegrationId>;

export const DownloadId = brandedId("DownloadId");
export type DownloadId = z.infer<typeof DownloadId>;

export const TaskId = brandedId("TaskId");
export type TaskId = z.infer<typeof TaskId>;

export const StreamId = brandedId("StreamId");
export type StreamId = z.infer<typeof StreamId>;
